
; BEGIN:sales_901c440f-f4df-4b07-9ec2-ff6c30185eab
; queue:sales
[sales-queue]
musicclass=default
strategy=rrmemory
timeout=30
retry=5
wrapup_time=5
maxlen=20
member => PJSIP/agent_901c440ff4df4b079ec2ff6c30185eab

; END:sales_901c440f-f4df-4b07-9ec2-ff6c30185eab

; BEGIN:dental_07b303a7-3403-46f1-88ee-f89ff946e608
; queue:dental
[dental-queue]
musicclass=default
strategy=rrmemory
timeout=30
retry=5
wrapup_time=5
maxlen=20
member => PJSIP/agent_07b303a7340346f188eef89ff946e608

; END:dental_07b303a7-3403-46f1-88ee-f89ff946e608

; BEGIN:voice-2.0_912fa10a-ff8d-44ee-b0cf-eb21b04ee9c8
; queue:voice-2.0
[voice-2.0-queue]
musicclass=default
strategy=rrmemory
timeout=30
retry=5
wrapup_time=5
maxlen=20
member => PJSIP/agent_912fa10aff8d44eeb0cfeb21b04ee9c8

; END:voice-2.0_912fa10a-ff8d-44ee-b0cf-eb21b04ee9c8

; BEGIN:voice-2.0_67ca2dca-5f1c-4628-b784-61b6ebf54bdd
; queue:voice-2.0
[voice-2.0-queue]
musicclass=default
strategy=rrmemory
timeout=30
retry=5
wrapup_time=5
maxlen=20
member => PJSIP/agent_67ca2dca5f1c4628b78461b6ebf54bdd

; END:voice-2.0_67ca2dca-5f1c-4628-b784-61b6ebf54bdd
