[general]
initial_silence = 2500       ; Máximo silencio inicial antes de colgar (2.5 seg)
greeting = 2000              ; Máxima duración del saludo para considerarlo HUMANO (2 seg)
after_greeting_silence = 1000; Silencio necesario después del saludo para decidir (1 seg)
total_analysis_time = 4000   ; Tiempo máximo total para el análisis (4 seg)
min_word_length = 100        ; Duración mínima de una palabra (100ms)
between_words_silence = 50   ; Silencio mínimo entre palabras (50ms)
maximum_number_of_words = 4  ; Si dicen más de 4 palabras seguidas, asume que es BUZÓN
